apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-hub
  namespace: bosta-insight-hub
  labels:
    app: insight-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insight-hub
  template:
    metadata:
      labels:
        app: insight-hub
    spec:
      containers:
      - name: insight-hub
        image: bosta/insight-hub:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: PORT
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: MYSQL_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: MYSQL_DATABASE
        - name: DELIVERIES_MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: DELIVERIES_MYSQL_HOST
        - name: DELIVERIES_MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: DELIVERIES_MYSQL_PORT
        - name: DELIVERIES_MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: DELIVERIES_MYSQL_DATABASE
        - name: DELIVERIES_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: MYSQL_USER
        - name: DELIVERIES_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: MYSQL_PASSWORD
        - name: REDIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: insight-hub-config
              key: REDIS_HOSTNAME
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: OPENAI_API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: JWT_SECRET
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: insight-hub-secrets
              key: MYSQL_PASSWORD
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: charts-storage
          mountPath: /app/public/charts
      volumes:
      - name: charts-storage
        emptyDir: {}