apiVersion: v1
kind: Secret
metadata:
  name: insight-hub-secrets
  namespace: bosta-insight-hub
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  OPENAI_API_KEY: ""  # echo -n "your-openai-key" | base64
  JWT_SECRET: ""      # echo -n "your-jwt-secret" | base64
  MYSQL_USER: ""      # echo -n "your-mysql-user" | base64
  MYSQL_PASSWORD: ""  # echo -n "your-mysql-password" | base64